# Generated by Django 4.2 on 2026-04-09 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('tipo_curso', models.CharField(choices=[('Curso Completo', 'Curso Completo'), ('Reforzamiento', 'Reforzamiento')], max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('esta_aprobado', models.BooleanField(default=False)),
                ('monto_total_curso', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
        ),
    ]
