# Generated by Django 4.2 on 2026-04-14 22:24

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('instructor', 'Instructor'), ('secretaria', 'Secretaria'), ('cajero', 'Cajero'), ('consulta', 'Solo Consulta')], default='consulta', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_matricula', models.DateField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=10)),
                ('nacionalidad', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('direccion', models.CharField(max_length=200)),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
                ('telefono_convencional', models.CharField(max_length=100)),
                ('telefono_movil', models.CharField(max_length=100)),
                ('nivel_educativo', models.CharField(choices=[('Primaria', 'Primaria'), ('Secundaria', 'Secundaria'), ('Universidad', 'Universidad'), ('Profesional', 'Profesional')], max_length=50)),
                ('profesion_u_oficio', models.CharField(max_length=100)),
                ('en_caso_de_emrgencia', models.CharField(max_length=100)),
                ('telefono_emergencia', models.CharField(max_length=100)),
                ('modalidad', models.CharField(choices=[('Regular', 'Regular'), ('Extraordinario', 'Extraordinario')], max_length=50)),
                ('horario', models.CharField(choices=[('8AM A 10AM', '8AM A 10AM'), ('10AM A 12PM', '10AM A 12PM'), ('12PM A 02PM', '12PM A 02PM'), ('04PM A 06PM', '04PM A 06PM')], max_length=50)),
                ('tipo_pago', models.CharField(choices=[('Pago_completo', 'Pago Completo'), ('Anticipo', 'Anticipo'), ('Beneficio', 'Beneficio')], max_length=50)),
                ('tipo_curso', models.CharField(choices=[('Curso_avanzado', 'avanzado'), ('Reforzamiento', 'Reforzamiento')], max_length=50)),
                ('categoria', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3')], max_length=50)),
                ('apariconia', models.CharField(choices=[('Redes_Sociales', 'Facebook'), ('Referido', 'Referido'), ('Sitio_Web', 'Boleta'), ('otro', 'Otro')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_recibo', models.CharField(max_length=50, unique=True)),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pagado', 'Pagado'), ('anticipo', 'Anticipo')], max_length=20)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia Bancaria'), ('tarjeta', 'Tarjeta de Crédito/Débito'), ('cheque', 'Cheque')], max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibos', to='app_escuela.matricula')),
            ],
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examen_practico', models.IntegerField(blank=True, null=True)),
                ('examen_teorico', models.IntegerField(blank=True, null=True)),
                ('Matricula', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='app_escuela.matricula')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('Matricula', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendario', to='app_escuela.matricula')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
