# Generated by Django 4.2 on 2026-05-14 19:04

from decimal import Decimal
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.PositiveIntegerField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=10)),
                ('nacionalidad', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('direccion', models.CharField(max_length=200)),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
                ('telefono_movil', models.CharField(max_length=100)),
                ('nivel_educativo', models.CharField(choices=[('Primaria', 'Primaria'), ('Secundaria', 'Secundaria'), ('Universidad', 'Universidad'), ('Profesional', 'Profesional')], max_length=50)),
                ('nombre_emergencia', models.CharField(max_length=100)),
                ('telefono_emergencia', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('numero_telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('experiencia', models.TextField(blank=True, null=True)),
                ('edad', models.PositiveIntegerField(blank=True, null=True)),
                ('categoria_vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructores', to='app_escuela.categoriavehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado')], default='pendiente', max_length=20)),
                ('modalidad', models.CharField(choices=[('Regular', 'Regular'), ('Extraordinario', 'Extraordinario')], max_length=50)),
                ('horario', models.CharField(choices=[('06AM', '06:00 AM'), ('08AM', '08:00 AM'), ('10AM', '10:00 AM'), ('12PM', '12:00 PM'), ('04PM', '04:00 PM')], max_length=10)),
                ('tipo_curso', models.CharField(choices=[('Principiante', 'Principiante'), ('Intermedio', 'Intermedio'), ('Avanzado', 'Avanzado')], max_length=50)),
                ('horas_reforzamiento', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('aparicion', models.CharField(choices=[('Redes_Sociales', 'Redes Sociales'), ('Referido', 'Referido'), ('Sitio_Web', 'Sitio Web'), ('otro', 'otro')], max_length=50)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matriculas', to='app_escuela.categoriavehiculo')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='app_escuela.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='PlanEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_curso', models.CharField(choices=[('Principiante', 'Principiante'), ('Intermedio', 'Intermedio'), ('Avanzado', 'Avanzado')], max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Plan de Estudio',
                'verbose_name_plural': 'Planes de Estudios',
                'ordering': ['tipo_curso', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ValorCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_curso', models.CharField(choices=[('Principiante', 'Principiante'), ('Intermedio', 'Intermedio'), ('Avanzado', 'Avanzado')], max_length=50)),
                ('precio_hora', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_horas', models.PositiveIntegerField(default=15)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Valor del Curso',
                'verbose_name_plural': 'Valores de Cursos',
                'ordering': ['-fecha_modificacion'],
            },
        ),
        migrations.CreateModel(
            name='TemaPlanEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('orden', models.PositiveSmallIntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
                ('plan_estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temas', to='app_escuela.planestudio')),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temas',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SubtemaPlanEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('orden', models.PositiveSmallIntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtemas', to='app_escuela.temaplanestudio')),
            ],
            options={
                'verbose_name': 'Subtema',
                'verbose_name_plural': 'Subtemas',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_recibo', models.CharField(max_length=50, unique=True)),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateField(default=django.utils.timezone.now)),
                ('tipo_pago', models.CharField(choices=[('completo', 'Completo'), ('anticipo', 'Anticipo'), ('beneficio', 'Beneficio')], max_length=20)),
                ('cantidad', models.PositiveSmallIntegerField(default=15)),
                ('monto_unitario', models.DecimalField(decimal_places=2, default=Decimal('433.33'), max_digits=10)),
                ('concepto', models.CharField(default='Pago de curso', max_length=200)),
                ('estado', models.CharField(choices=[('pagado', 'Pagado'), ('anticipo', 'Anticipo'), ('anulado', 'Anulado')], default='anticipo', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibos', to='app_escuela.matricula')),
                ('valor_curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recibos', to='app_escuela.valorcurso')),
            ],
            options={
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.CreateModel(
            name='ProgresoTema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante_completado', models.BooleanField(default=False)),
                ('instructor_completado', models.BooleanField(default=False)),
                ('desbloqueado', models.BooleanField(default=False)),
                ('completado', models.BooleanField(default=False)),
                ('fecha_estudiante', models.DateTimeField(blank=True, null=True)),
                ('fecha_instructor', models.DateTimeField(blank=True, null=True)),
                ('fecha_admin_edit', models.DateTimeField(blank=True, null=True)),
                ('matricula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progresos_temas', to='app_escuela.matricula')),
                ('subtema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos_estudiantes', to='app_escuela.subtemaplanestudio')),
            ],
            options={
                'ordering': ['subtema__tema__orden', 'subtema__orden'],
                'unique_together': {('matricula', 'subtema')},
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('falta_estudiante', 'El estudiante no ha marcado su tema'), ('falta_instructor', 'El instructor no ha marcado la clase'), ('tema_bloqueado', 'Tema bloqueado'), ('intervencion_admin', 'El admin realizó una intervención'), ('plan_completado', 'El estudiante completó todo el plan')], max_length=30)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
                ('tema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_escuela.temaplanestudio')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_nota', models.CharField(choices=[('practico', 'Examen práctico'), ('teorico', 'Examen teórico')], default='practico', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('nota', models.CharField(max_length=10)),
                ('comentario', models.CharField(default='Comentario', max_length=50)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_registradas', to='app_escuela.instructor')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='app_escuela.matricula')),
                ('plan_de_estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='app_escuela.planestudio')),
            ],
            options={
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.AddField(
            model_name='matricula',
            name='plan_de_estudio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matriculas', to='app_escuela.planestudio'),
        ),
        migrations.CreateModel(
            name='HistorialPlanEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=50)),
                ('valor_anterior_estudiante', models.BooleanField(null=True)),
                ('valor_anterior_instructor', models.BooleanField(null=True)),
                ('valor_nuevo_estudiante', models.BooleanField(null=True)),
                ('valor_nuevo_instructor', models.BooleanField(null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('progreso_tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='app_escuela.progresotema')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('numero_clase', models.PositiveSmallIntegerField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada'), ('inasistencia', 'Inasistencia'), ('reprogramada', 'Reprogramada')], default='pendiente', max_length=20)),
                ('es_examen', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='app_escuela.instructor')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='app_escuela.matricula')),
                ('modulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases', to='app_escuela.planestudio')),
            ],
            options={
                'ordering': ['fecha', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('As_calendario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_escuela.calendario')),
                ('As_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_escuela.estudiante')),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='estudiante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='app_escuela.estudiante'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='app_escuela.instructor'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='app_escuela.rol'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
