# Generated by Django 4.2.11 on 2026-05-12 20:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_escuela', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
