# Generated by Django 4.2 on 2026-05-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_escuela', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notas',
            name='comentario',
            field=models.CharField(default='Comentario', max_length=50),
        ),
    ]
