# Generated by Django 4.2 on 2026-05-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_escuela', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='km_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='km_inicial',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='km_recorridos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
