# Generated by Django 4.2.11 on 2026-04-21 16:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_escuela', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibo',
            name='cantidad',
            field=models.PositiveSmallIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='recibo',
            name='concepto',
            field=models.CharField(default='Pago de curso', max_length=200),
        ),
        migrations.AddField(
            model_name='recibo',
            name='horas_reforzamiento',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recibo',
            name='monto_cordobas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='recibo',
            name='monto_dolares',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='recibo',
            name='monto_unitario',
            field=models.DecimalField(decimal_places=2, default=Decimal('433.33'), max_digits=10),
        ),
        migrations.AddField(
            model_name='recibo',
            name='tasa_cambio',
            field=models.DecimalField(decimal_places=2, default=Decimal('36.60'), max_digits=10),
        ),
        migrations.AddField(
            model_name='recibo',
            name='tipo_curso',
            field=models.CharField(default='regular', max_length=20),
        ),
        migrations.AddField(
            model_name='recibo',
            name='tipo_pago',
            field=models.CharField(choices=[('completo', 'Completo'), ('anticipo', 'Anticipo'), ('beneficio', 'Beneficio')], default='anticipo', max_length=20),
        ),
    ]
