# Generated by Django 4.2 on 2026-04-15 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_escuela', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='edad',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('instructor', 'Instructor'), ('secretaria', 'Secretaria'), ('cajero', 'Cajero'), ('consulta', 'Solo Consulta')], default='admin', max_length=20),
        ),
    ]
