# Generated by Django 4.2 on 2026-05-19 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_escuela', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamenTeorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('habilitado', 'Habilitado'), ('realizado', 'Realizado')], default='pendiente', max_length=20)),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fecha_habilitado', models.DateTimeField(blank=True, null=True)),
                ('fecha_realizado', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OpcionPreguntaExamenTeorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('es_correcta', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaExamenTeorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='categoria_vehiculo',
        ),
        migrations.AddField(
            model_name='instructor',
            name='antecedentes_penales',
            field=models.CharField(choices=[('Si', 'Sí'), ('No', 'No')], default='No', max_length=20),
        ),
        migrations.AddField(
            model_name='instructor',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='categoria_instructor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='cedula',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='centro_trabajo',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='curso_aprobado_instructor',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='fecha_salida',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='infracciones_resoluciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='motivo_salida',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='nivel_escolar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notas',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RespuestaExamenTeorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correcta', models.BooleanField(default=False)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='app_escuela.examenteorico')),
                ('opcion_seleccionada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_escuela.opcionpreguntaexamenteorico')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_escuela.preguntaexamenteorico')),
            ],
        ),
        migrations.AddField(
            model_name='opcionpreguntaexamenteorico',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='app_escuela.preguntaexamenteorico'),
        ),
        migrations.AddField(
            model_name='examenteorico',
            name='habilitado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examenes_teoricos_habilitados', to='app_escuela.instructor'),
        ),
        migrations.AddField(
            model_name='examenteorico',
            name='matricula',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='examen_teorico', to='app_escuela.matricula'),
        ),
    ]
