# Generated by Django 4.2.11 on 2026-05-13 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_escuela', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('matriculado', 'Matriculado')], default='pendiente', max_length=20),
        ),
    ]
