# Generated by Django 4.2 on 2026-04-10 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_escuela', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=10)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('direccion', models.CharField(max_length=200)),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
                ('nivel_educativo', models.CharField(max_length=50)),
                ('oficio', models.CharField(max_length=100)),
                ('numero_telefono', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('grado', models.CharField(max_length=50)),
                ('nombre_padre', models.CharField(max_length=100)),
                ('n_emergencia', models.CharField(max_length=100)),
                ('apariconia', models.CharField(max_length=100)),
                ('f_matricula', models.DateField(auto_now_add=True)),
                ('categoria', models.CharField(max_length=50)),
                ('tipo_pago', models.CharField(max_length=50)),
                ('tipo_curso', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Estudiante',
        ),
    ]
