# Generated by Django 4.2 on 2026-05-18 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_escuela', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamenTeorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('habilitado', 'Habilitado'), ('realizado', 'Realizado')], default='pendiente', max_length=20)),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fecha_habilitado', models.DateTimeField(blank=True, null=True)),
                ('fecha_realizado', models.DateTimeField(blank=True, null=True)),
                ('habilitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examenes_teoricos_habilitados', to='app_escuela.instructor')),
                ('matricula', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='examen_teorico', to='app_escuela.matricula')),
            ],
        ),
        migrations.CreateModel(
            name='OpcionPreguntaExamenTeorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('es_correcta', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaExamenTeorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('tipo_curso', models.CharField(choices=[('Principiante', 'Principiante'), ('Intermedio', 'Intermedio'), ('Avanzado', 'Avanzado')], max_length=50)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaExamenTeorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correcta', models.BooleanField(default=False)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='app_escuela.examenteorico')),
                ('opcion_seleccionada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_escuela.opcionpreguntaexamenteorico')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_escuela.preguntaexamenteorico')),
            ],
        ),
        migrations.AddField(
            model_name='opcionpreguntaexamenteorico',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='app_escuela.preguntaexamenteorico'),
        ),
    ]
