# Generated by Django 4.2.11 on 2026-05-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_escuela', '0002_asistencia_km_final_asistencia_km_inicial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_por_alumno', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
