# Generated by Django 4.2 on 2026-05-18 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_escuela', '0002_examenteorico_opcionpreguntaexamenteorico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preguntaexamenteorico',
            name='tipo_curso',
        ),
    ]
