# Generated by Django 4.2.11 on 2026-05-12 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_escuela', '0002_matricula_fecha_registro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matricula',
            name='planEstudio',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='valorCurso',
        ),
    ]
