# Generated by Django 4.2 on 2026-04-21 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_escuela', '0002_recibo_cantidad_recibo_concepto_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='calendario',
            unique_together=set(),
        ),
    ]
