# Generated by Django 4.2.11 on 2026-05-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_escuela', '0002_alter_matricula_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='instructores/'),
        ),
    ]
