# Generated by Django 4.2 on 2026-04-15 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_escuela', '0002_alter_matricula_edad_alter_usuario_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matricula',
            name='telefono_convencional',
        ),
    ]
