# Generated by Django 4.2.11 on 2026-05-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_escuela', '0003_remove_matricula_planestudio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='horas_reforzamiento',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
