# Generated by Django 4.2.11 on 2026-05-25 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_escuela', '0003_pagoinstructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('cargo', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('gerente', 'Gerente'), ('director', 'Director'), ('secretaria', 'Secretaria'), ('otro', 'Otro')], max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
