# Generated by Django 4.2 on 2026-04-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_escuela', '0003_remove_matricula_telefono_convencional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='apariconia',
            field=models.CharField(choices=[('Redes_Sociales', 'Redes_Sociales'), ('Referido', 'Referido'), ('Sitio_Web', 'Sitio_web'), ('otro', 'Otro')], max_length=100),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='categoria',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=50),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='horario',
            field=models.CharField(choices=[('6AM A 8AM', '6AM A 8AM'), ('8AM A 10AM', '8AM A 10AM'), ('10AM A 12PM', '10AM A 12PM'), ('12PM A 2PM', '12PM A 2PM'), ('4PM A 6PM', '4PM A 6PM')], max_length=50),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='tipo_curso',
            field=models.CharField(choices=[('Curso_avanzado', 'Curso Avanzado'), ('Reforzamiento', 'Reforzamiento')], max_length=50),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='tipo_pago',
            field=models.CharField(choices=[('Pago_completo', 'Pago_completo'), ('Anticipo', 'Anticipo'), ('Beneficio', 'Beneficio')], max_length=50),
        ),
    ]
