# Generated by Django 4.2 on 2026-04-21 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_escuela', '0003_alter_calendario_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendario',
            options={'ordering': ['fecha', 'hora_inicio']},
        ),
        migrations.AddField(
            model_name='calendario',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calendario',
            name='numero_clase',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='calendario',
            index=models.Index(fields=['instructor', 'fecha'], name='app_escuela_instruc_49a13a_idx'),
        ),
        migrations.AddIndex(
            model_name='calendario',
            index=models.Index(fields=['matricula'], name='app_escuela_matricu_caf876_idx'),
        ),
    ]
