# Generated by Django 4.2 on 2026-05-18 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_escuela', '0003_remove_preguntaexamenteorico_tipo_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notas',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
