# Generated by Django 4.2.11 on 2026-05-18 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_escuela', '0003_instructor_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='antecedentes_penales',
            field=models.CharField(choices=[('Si', 'Sí'), ('No', 'No')], default='No', max_length=20),
        ),
        migrations.AddField(
            model_name='instructor',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='cedula',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='centro_trabajo',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='curso_aprobado_instructor',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='fecha_salida',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='infracciones_resoluciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='motivo_salida',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='nivel_escolar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
