# Generated by Django 4.2 on 2026-04-23 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_escuela', '0004_alter_calendario_options_calendario_hora_fin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendario',
            name='asistio',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='calendario',
            name='justificada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calendario',
            name='motivo_justificacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
