# Generated by Django 4.2.11 on 2026-05-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_escuela', '0004_instructor_antecedentes_penales_instructor_cargo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='categoria_vehiculo',
        ),
        migrations.AddField(
            model_name='instructor',
            name='categoria_instructor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
