# Generated by Django 4.2 on 2026-04-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_escuela', '0004_alter_matricula_apariconia_alter_matricula_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='apariconia',
            field=models.CharField(choices=[('Redes_Sociales', 'Redes Sociales'), ('Referido', 'Referido'), ('Sitio_Web', 'Sitio Web'), ('otro', 'Otro')], max_length=100),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='tipo_curso',
            field=models.CharField(choices=[('Curso_regular', 'Curso Regular'), ('Reforzamiento', 'Reforzamiento')], max_length=50),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='tipo_pago',
            field=models.CharField(choices=[('Pago_completo', 'Pago completo'), ('Anticipo', 'Anticipo'), ('Beneficio', 'Beneficio')], max_length=50),
        ),
    ]
