# Generated by Django 4.2.11 on 2026-05-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_escuela', '0004_matricula_horas_reforzamiento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendario',
            options={'ordering': ['fecha', 'hora_inicio']},
        ),
        migrations.RemoveField(
            model_name='calendario',
            name='numero_dias',
        ),
        migrations.AddField(
            model_name='calendario',
            name='es_examen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calendario',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada'), ('inasistencia', 'Inasistencia'), ('reprogramada', 'Reprogramada')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='calendario',
            name='hora_fin',
            field=models.TimeField(default='10:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calendario',
            name='hora_inicio',
            field=models.TimeField(default='06:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calendario',
            name='numero_clase',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calendario',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
