# Generated by Django 4.2.11 on 2026-05-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_escuela', '0004_cargoinstitucional'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='planestudio',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
