# Generated by Django 4.2.11 on 2026-05-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_escuela', '0005_instructor_activo_planestudio_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('matriculado', 'Matriculado'), ('finalizado', 'Finalizado')], default='pendiente', max_length=20),
        ),
    ]
