# Generated by Django 4.2 on 2026-04-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_escuela', '0005_calendario_asistio_calendario_justificada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='cedula',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='correo_electronico',
            field=models.EmailField(max_length=254),
        ),
    ]
