# Generated by Django 4.2 on 2026-04-20 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_escuela', '0005_alter_matricula_apariconia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matricula',
            name='tipo_pago',
        ),
    ]
