# Generated by Django 4.2 on 2026-04-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_escuela', '0005_alter_matricula_apariconia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibo',
            name='cantidad',
            field=models.PositiveSmallIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='recibo',
            name='concepto',
            field=models.CharField(default='Pago de curso', max_length=200),
        ),
        migrations.AddField(
            model_name='recibo',
            name='horas_reforzamiento',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recibo',
            name='monto_cordobas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='recibo',
            name='monto_dolares',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='recibo',
            name='monto_unitario',
            field=models.DecimalField(decimal_places=2, default=433.33, max_digits=10),
        ),
        migrations.AddField(
            model_name='recibo',
            name='tasa_cambio',
            field=models.DecimalField(decimal_places=2, default=36.6, max_digits=10),
        ),
        migrations.AddField(
            model_name='recibo',
            name='tipo_curso',
            field=models.CharField(default='regular', max_length=20),
        ),
        migrations.AddField(
            model_name='recibo',
            name='tipo_pago',
            field=models.CharField(choices=[('completo', 'Completo'), ('anticipo', 'Anticipo'), ('beneficio', 'Beneficio')], default='anticipo', max_length=20),
        ),
    ]
