# Generated by Django 4.2.11 on 2026-05-19 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_escuela', '0004_alter_notas_comentario'),
        ('app_escuela', '0005_remove_instructor_categoria_vehiculo_and_more'),
    ]

    operations = [
    ]
