# Generated by Django 4.2 on 2026-04-14 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_escuela', '0006_instructor_especialidad_alter_matricula_tipo_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matricula',
            name='numero_telefono',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='oficio',
        ),
        migrations.AddField(
            model_name='matricula',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='nacionalidad',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matricula',
            name='profesion_o_oficio',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='matricula',
            name='apariconia',
            field=models.CharField(choices=[('Redes_Sociales', 'Facebook'), ('Referido', 'Referido'), ('Sitio_Web', 'Boleta'), ('otro', 'Otro')], max_length=100),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='nivel_educativo',
            field=models.CharField(choices=[('Primaria', 'Primaria'), ('Secundaria', 'Secundaria'), ('Universidad', 'Universidad'), ('Profesional', 'Profesional')], max_length=50),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=10),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='tipo_curso',
            field=models.CharField(choices=[('Curso_avanzado', 'avanzado'), ('Reforzamiento', 'Reforzamiento')], max_length=50),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='tipo_pago',
            field=models.CharField(choices=[('Pago_completo', 'Pago Completo'), ('Anticipo', 'Anticipo'), ('Beneficio', 'Beneficio')], max_length=50),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia Bancaria'), ('tarjeta', 'Tarjeta de Crédito/Débito'), ('cheque', 'Cheque')], max_length=20),
        ),
    ]
