# Generated by Django 4.2 on 2026-06-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_escuela', '0006_alter_matricula_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='foto',
        ),
        migrations.AddField(
            model_name='instructor',
            name='foto_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
