# Generated by Django 4.2 on 2026-04-23 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_escuela', '0006_alter_matricula_cedula_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='horas_reforzamiento',
            field=models.IntegerField(blank=True, null=True, verbose_name='Horas de Reforzamiento'),
        ),
    ]
