# Generated by Django 4.2 on 2026-06-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_escuela', '0007_remove_instructor_foto_instructor_foto_base64'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='instructores/'),
        ),
    ]
