# Generated by Django 4.2 on 2026-04-23 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_escuela', '0007_matricula_horas_reforzamiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='horario',
            field=models.CharField(choices=[('6AM', '6AM'), ('8AM', '8AM'), ('10AM', '10AM'), ('12PM', '12PM'), ('02PM', '02PM'), ('04PM', '04PM')], max_length=50),
        ),
    ]
