# Generated by Django 4.2 on 2026-06-01 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_escuela', '0008_instructor_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='foto',
        ),
    ]
