# Generated by Django 4.2 on 2026-04-23 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_escuela', '0008_alter_matricula_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
