# Generated by Django 4.2.11 on 2026-05-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_escuela', '0009_matricula_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='horario',
            field=models.CharField(choices=[('06AM', '06AM'), ('08AM', '08AM'), ('10AM', '10AM'), ('12PM', '12PM'), ('04PM', '04PM')], max_length=50),
        ),
    ]
