# Generated by Django 4.2 on 2026-06-11 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_escuela', '0009_remove_instructor_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtemaplanestudio',
            name='titulo',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='temaplanestudio',
            name='titulo',
            field=models.CharField(max_length=300),
        ),
    ]
