# Generated by Django 4.2.11 on 2026-05-06 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_escuela', '0010_alter_matricula_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matricula', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='f_matricula',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='horas_reforzamiento',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='tipo_curso',
            field=models.CharField(choices=[('Principiante', 'Principiante'), ('Intermedio', 'Intermedio'), ('Avanzado', 'Avanzado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='fecha_pago',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='tipo_curso',
            field=models.CharField(default='Principiante', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('instructor', 'Instructor'), ('estudiante', 'Estudiante')], default='admin', max_length=20),
        ),
    ]
