# Generated by Django 4.2 on 2026-06-15 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_escuela', '0010_alter_subtemaplanestudio_titulo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecuenciaCodigoEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='estudiante', max_length=50, unique=True)),
                ('ultimo_codigo', models.PositiveIntegerField(default=1984)),
            ],
        ),
        migrations.AddField(
            model_name='estudiante',
            name='codigo_estudiante',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
