# Generated by Django 4.2 on 2026-05-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_escuela', '0011_matricula_usuario_alter_matricula_f_matricula_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado')], default='pendiente', max_length=20),
        ),
    ]
