# Generated by Django 4.2 on 2026-06-16 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_escuela', '0011_secuenciacodigoestudiante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secuenciacodigoestudiante',
            name='ultimo_codigo',
            field=models.PositiveIntegerField(default=2129),
        ),
    ]
