# Generated by Django 4.2 on 2026-06-17 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_escuela', '0012_alter_secuenciacodigoestudiante_ultimo_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgresoClaseTema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante_completado', models.BooleanField(default=False)),
                ('instructor_completado', models.BooleanField(default=False)),
                ('completado', models.BooleanField(default=False)),
                ('fecha_estudiante', models.DateTimeField(blank=True, null=True)),
                ('fecha_instructor', models.DateTimeField(blank=True, null=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('calendario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos_tema_dia', to='app_escuela.calendario')),
                ('progreso_tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks_por_clase', to='app_escuela.progresotema')),
            ],
            options={
                'ordering': ['calendario__fecha', 'calendario__hora_inicio'],
                'unique_together': {('calendario', 'progreso_tema')},
            },
        ),
    ]
