# Generated by Django 4.2 on 2026-06-18 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_escuela', '0013_progresoclasetema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='modalidad',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Extraordinario', 'Extraordinario'), ('Mixto', 'Mixto')], max_length=50),
        ),
    ]
