# Generated by Django 4.2 on 2026-06-24 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_escuela', '0014_alter_matricula_modalidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='incluye_examen_policial',
            field=models.BooleanField(default=False),
        ),
    ]