# Generated by Django 4.2 on 2026-06-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_escuela', '0015_matricula_incluye_examen_policial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendario',
            name='estado',
            field=models.CharField(
                choices=[
                    ('pendiente', 'Pendiente'),
                    ('completada', 'Completada'),
                    ('inasistencia', 'Inasistencia'),
                    ('reprogramada', 'Reprogramada'),
                    ('cancelada', 'Cancelada'),
                ],
                default='pendiente',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='correo_electronico',
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                unique=True,
            ),
        ),
    ]