# Generated by Django 4.2 on 2026-07-03 00:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('app_escuela', '0016_alter_calendario_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntentoExamenTeorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_intento', models.PositiveSmallIntegerField()),
                ('estado', models.CharField(choices=[('habilitado', 'Habilitado'), ('iniciado', 'Iniciado'), ('realizado', 'Realizado')], default='habilitado', max_length=20)),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fecha_habilitado', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_iniciado', models.DateTimeField(blank=True, null=True)),
                ('fecha_realizado', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['examen_id', 'numero_intento'],
            },
        ),
        migrations.CreateModel(
            name='PreguntaIntentoExamenTeorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['intento_id', 'orden'],
            },
        ),
        migrations.AlterModelOptions(
            name='respuestaexamenteorico',
            options={'ordering': ['intento_id', 'pregunta_id']},
        ),
        migrations.AddField(
            model_name='respuestaexamenteorico',
            name='fecha_respuesta',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='respuestaexamenteorico',
            name='opcion_seleccionada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respuestas_seleccionadas', to='app_escuela.opcionpreguntaexamenteorico'),
        ),
        migrations.AlterField(
            model_name='respuestaexamenteorico',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respuestas_examen', to='app_escuela.preguntaexamenteorico'),
        ),
        migrations.AddField(
            model_name='preguntaintentoexamenteorico',
            name='intento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas_asignadas', to='app_escuela.intentoexamenteorico'),
        ),
        migrations.AddField(
            model_name='preguntaintentoexamenteorico',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_examen', to='app_escuela.preguntaexamenteorico'),
        ),
        migrations.AddField(
            model_name='intentoexamenteorico',
            name='examen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='app_escuela.examenteorico'),
        ),
        migrations.AddField(
            model_name='respuestaexamenteorico',
            name='intento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='app_escuela.intentoexamenteorico'),
        ),
        migrations.AddIndex(
            model_name='respuestaexamenteorico',
            index=models.Index(fields=['examen', 'intento'], name='idx_respuesta_examen_intento'),
        ),
        migrations.AddIndex(
            model_name='preguntaintentoexamenteorico',
            index=models.Index(fields=['intento', 'orden'], name='idx_preguntas_intento_orden'),
        ),
        migrations.AddConstraint(
            model_name='preguntaintentoexamenteorico',
            constraint=models.UniqueConstraint(fields=('intento', 'orden'), name='orden_unico_por_intento'),
        ),
        migrations.AddConstraint(
            model_name='preguntaintentoexamenteorico',
            constraint=models.CheckConstraint(check=models.Q(('orden__gte', 1)), name='orden_pregunta_mayor_cero'),
        ),
        migrations.AddIndex(
            model_name='intentoexamenteorico',
            index=models.Index(fields=['examen', '-numero_intento'], name='idx_examen_ultimo_intento'),
        ),
        migrations.AddIndex(
            model_name='intentoexamenteorico',
            index=models.Index(fields=['estado', 'fecha_habilitado'], name='idx_intento_estado_fecha'),
        ),
        migrations.AddConstraint(
            model_name='intentoexamenteorico',
            constraint=models.UniqueConstraint(fields=('examen', 'numero_intento'), name='intento_unico_por_examen'),
        ),
        migrations.AddConstraint(
            model_name='intentoexamenteorico',
            constraint=models.CheckConstraint(check=models.Q(('numero_intento__gte', 1)), name='numero_intento_mayor_cero'),
        ),
    ]
