# Generated by Django 4.2 on 2026-07-06 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_escuela', '0018_migrar_intentos_historicos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recibo',
            name='estado',
        ),
        migrations.AddConstraint(
            model_name='preguntaintentoexamenteorico',
            constraint=models.UniqueConstraint(fields=('intento', 'pregunta'), name='pregunta_unica_por_intento'),
        ),
    ]
