# Generated by Django 4.2 on 2026-07-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_escuela', '0019_remove_recibo_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='fecha_finalizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
