# Generated by Django 4.2 on 2026-07-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_escuela', '0021_completar_fechas_finalizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='horario',
            field=models.CharField(choices=[('06AM', '06:00 AM'), ('08AM', '08:00 AM'), ('10AM', '10:00 AM'), ('12PM', '12:00 PM'), ('02PM', '02:00 PM'), ('04PM', '04:00 PM')], max_length=10),
        ),
    ]
