# Generated by Django 4.2 on 2026-07-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_escuela', '0022_alter_matricula_horario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendario',
            options={'ordering': ['fecha', 'hora_inicio', 'id']},
        ),
        migrations.AddIndex(
            model_name='calendario',
            index=models.Index(fields=['fecha', 'hora_inicio'], name='cal_fecha_hora_idx'),
        ),
        migrations.AddIndex(
            model_name='calendario',
            index=models.Index(fields=['instructor', 'fecha', 'hora_inicio'], name='cal_inst_fecha_idx'),
        ),
    ]
