# Generated by Django 4.2 on 2026-07-21 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_escuela', '0023_alter_calendario_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notificacion',
            name='notificacion_unica_por_tema_tipo',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='progreso_tema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='app_escuela.progresotema'),
        ),
        migrations.AddConstraint(
            model_name='notificacion',
            constraint=models.UniqueConstraint(fields=('estudiante', 'progreso_tema', 'tipo'), name='notificacion_unica_por_progreso_tipo'),
        ),
    ]
