# Generated by Django 4.2 on 2026-07-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_escuela', '0026_matricula_fechas_programadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='fecha_desactivacion_usuario',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
