# Generated by Django 4.2 on 2026-08-18 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_escuela', '0027_matricula_fecha_desactivacion_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionCertificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimo_asiento', models.PositiveIntegerField(verbose_name='Último número de asiento')),
                ('folio_actual', models.PositiveIntegerField(verbose_name='Folio actual')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configuraciones_certificado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de certificados',
                'verbose_name_plural': 'Configuración de certificados',
            },
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('normal', 'Curso Principiante'), ('reforzamiento', 'Principiante con reforzamiento')], default='normal', max_length=20)),
                ('numero_asiento', models.PositiveIntegerField(unique=True)),
                ('numero_folio', models.PositiveIntegerField(db_index=True)),
                ('numero_libro', models.PositiveIntegerField(db_index=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_finalizacion', models.DateField()),
                ('nota_teorica', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nota_practica', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reforzamiento_confirmado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('confirmado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificados_confirmados', to=settings.AUTH_USER_MODEL)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificados', to='app_escuela.estudiante')),
                ('matricula', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='certificado', to='app_escuela.matricula')),
            ],
            options={
                'ordering': ['-numero_asiento'],
            },
        ),
        migrations.AddIndex(
            model_name='certificado',
            index=models.Index(fields=['numero_libro', 'numero_folio', 'numero_asiento'], name='cert_lib_fol_asi_idx'),
        ),
        migrations.AddConstraint(
            model_name='certificado',
            constraint=models.CheckConstraint(check=models.Q(('numero_asiento__gt', 0)), name='cert_asiento_mayor_cero'),
        ),
        migrations.AddConstraint(
            model_name='certificado',
            constraint=models.CheckConstraint(check=models.Q(('numero_folio__gt', 0)), name='cert_folio_mayor_cero'),
        ),
        migrations.AddConstraint(
            model_name='certificado',
            constraint=models.CheckConstraint(check=models.Q(('numero_libro__gt', 0)), name='cert_libro_mayor_cero'),
        ),
    ]
