# Generated by Django 4.2 on 2026-08-18 05:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_escuela', '0028_configuracioncertificado_certificado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibo',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='numero_recibo',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='tipo_pago',
            field=models.CharField(choices=[('completo', 'Completo'), ('anticipo', 'Anticipo'), ('beneficio', 'Beneficio'), ('credito', 'Crédito')], max_length=20),
        ),
    ]
