# Generated by Django 4.2 on 2026-08-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_escuela', '0029_alter_recibo_monto_pagado_alter_recibo_numero_recibo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibo',
            name='tipo_pago',
            field=models.CharField(choices=[('completo', 'Completo'), ('anticipo', 'Anticipo'), ('descuento', 'Descuento'), ('credito', 'Crédito')], max_length=20),
        ),
    ]
