# Generated by Django 4.2 on 2026-08-19 03:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_escuela', '0030_alter_recibo_tipo_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendario_id', models.PositiveIntegerField(db_index=True, help_text='Identificador de la cita afectada, incluso si fue eliminada.')),
                ('accion', models.CharField(max_length=80)),
                ('detalle', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_calendario', to='app_escuela.instructor')),
                ('matricula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_calendario', to='app_escuela.matricula')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_calendario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='historialcalendario',
            index=models.Index(fields=['calendario_id', 'creado_en'], name='hist_calendario_fecha_idx'),
        ),
    ]
