# Generated by Django 4.2 on 2026-08-20 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_escuela', '0031_historialcalendario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_nombre', models.CharField(blank=True, max_length=150)),
                ('accion', models.CharField(max_length=100)),
                ('modulo', models.CharField(max_length=100)),
                ('detalle', models.TextField(blank=True)),
                ('metodo', models.CharField(blank=True, max_length=10)),
                ('ruta', models.CharField(blank=True, max_length=255)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('estado_http', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddIndex(
            model_name='registroauditoria',
            index=models.Index(fields=['-creado_en'], name='auditoria_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='registroauditoria',
            index=models.Index(fields=['modulo', '-creado_en'], name='auditoria_modulo_idx'),
        ),
        migrations.AddIndex(
            model_name='registroauditoria',
            index=models.Index(fields=['accion', '-creado_en'], name='auditoria_accion_idx'),
        ),
    ]
